# This file is generated by composer-plugin-nixify.
# Manual changes might be lost - proceed with caution!
{
  lib,
  php,
  phpPackages,
  unzip,
  stdenv,
  runCommandLocal,
  writeText,
  fetchurl,
  # Default fetcher.
  fetcher ? (args: fetchurl {inherit (args) name urls sha256;}),
}: src:
with lib; let
  data = builtins.fromJSON ''
        {
        "cacheEntries": [
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "brick_math-0.10.2.0",
                "urls": [
                    "https://api.github.com/repos/brick/math/zipball/459f2781e1a08d52ee56b0b1444086e038561e3f"
                ],
                "cacheFile": "brick/math/fc3801b79995ca2750189dd15609bb81d3cabbca.zip",
                "sha256": "77113779640ced089eb8a7e2475e925d5c7b48fcf129f921051666ee878f0f03"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "dflydev_dot-access-data-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/dflydev/dflydev-dot-access-data/zipball/f41715465d65213d644d3141a6a93081be5d3549"
                ],
                "cacheFile": "dflydev/dot-access-data/5872417a18bbb69b106dc09a3b09c46b193e0110.zip",
                "sha256": "b2ae92836d920d2a968b32acd80e1c39a1446c749ddae28dc806408c7096ebed"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "doctrine_deprecations-1.0.0.0",
                "urls": [
                    "https://api.github.com/repos/doctrine/deprecations/zipball/0e2a4f1f8cdfc7a92ec3b01c9334898c806b30de"
                ],
                "cacheFile": "doctrine/deprecations/0b11d410b30a1fca6ad657a01bbf1bf8cb37b15b.zip",
                "sha256": "0948892861e2470c164fb0c45063967417c4b9e527ea4cf2b987030b047061ea"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "doctrine_inflector-2.0.6.0",
                "urls": [
                    "https://api.github.com/repos/doctrine/inflector/zipball/d9d313a36c872fd6ee06d9a6cbcf713eaa40f024"
                ],
                "cacheFile": "doctrine/inflector/57c027282263baa14000cf3525eb68a5f0795e45.zip",
                "sha256": "12dae3b88886e0adde83b1d7338d2df7480620a0ec5ec8cde15935857b05defc"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "doctrine_lexer-2.1.0.0",
                "urls": [
                    "https://api.github.com/repos/doctrine/lexer/zipball/39ab8fcf5a51ce4b85ca97c7a7d033eb12831124"
                ],
                "cacheFile": "doctrine/lexer/b4234cb7c4536da25e7669362cfb87940f58d05f.zip",
                "sha256": "50bde7a5b68b6ef697044ed6256605a3bf19b106491dcbea5dc569041d9a6aa6"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "dragonmantank_cron-expression-3.3.2.0",
                "urls": [
                    "https://api.github.com/repos/dragonmantank/cron-expression/zipball/782ca5968ab8b954773518e9e49a6f892a34b2a8"
                ],
                "cacheFile": "dragonmantank/cron-expression/4f2cae11a28f521a6bbb27396bf433acc336909b.zip",
                "sha256": "e961b1c2dcc99c0b1a34f4501833cb0941208ae5e40ae1e7e7d08b3576b0fda2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "egulias_email-validator-3.2.5.0",
                "urls": [
                    "https://api.github.com/repos/egulias/EmailValidator/zipball/b531a2311709443320c786feb4519cfaf94af796"
                ],
                "cacheFile": "egulias/email-validator/fbd93f281d2a45219617370e886cd79b5143b67b.zip",
                "sha256": "ec59ebdc8df85e80c9a207c38b15fda8a84f38d5a25a2da5f017210b6e6b230c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "fruitcake_php-cors-1.2.0.0",
                "urls": [
                    "https://api.github.com/repos/fruitcake/php-cors/zipball/58571acbaa5f9f462c9c77e911700ac66f446d4e"
                ],
                "cacheFile": "fruitcake/php-cors/1de04ebee01b584ebc4c86dacbf172b3bc4ee77a.zip",
                "sha256": "a16a913bc20cbd2a26b114975e324dde53e897f068a4fbb8c33fcd467032b5a3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "graham-campbell_result-type-1.1.0.0",
                "urls": [
                    "https://api.github.com/repos/GrahamCampbell/Result-Type/zipball/a878d45c1914464426dc94da61c9e1d36ae262a8"
                ],
                "cacheFile": "graham-campbell/result-type/7fcdb89c98fdc16e9029a7634abb83d2a6e18464.zip",
                "sha256": "6b8717820fc9b49de9d9adb9cbccd1c35ffd9a3f341d767bf4c7902592565ef5"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "guzzlehttp_uri-template-1.0.1.0",
                "urls": [
                    "https://api.github.com/repos/guzzle/uri-template/zipball/b945d74a55a25a949158444f09ec0d3c120d69e2"
                ],
                "cacheFile": "guzzlehttp/uri-template/458dd37ed5ec454f8f2a0c65076b0672e09e4e3d.zip",
                "sha256": "0e369c50062d365469c4312eebd57cc5eeb33c0d5e3aae8a4db0a3d844266d0b"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "laravel_framework-9.51.0.0",
                "urls": [
                    "https://api.github.com/repos/laravel/framework/zipball/b81123134349a013a738a9f7f715c6ce99d5a414"
                ],
                "cacheFile": "laravel/framework/3833c7fa2d43f27168c261b43e3e5fc6dcd93522.zip",
                "sha256": "9abe18499d72c8a0b860905ca371197aba14066e3c667e5676f64dd8f901259c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "laravel_serializable-closure-1.3.0.0",
                "urls": [
                    "https://api.github.com/repos/laravel/serializable-closure/zipball/f23fe9d4e95255dacee1bf3525e0810d1a1b0f37"
                ],
                "cacheFile": "laravel/serializable-closure/728814a9e03933b6eed6a78910a61878db473045.zip",
                "sha256": "b4a13fa026d52a40e069eb16158536f2e3f8670f8ba867e8338b065ce0c5db37"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "league_commonmark-2.3.8.0",
                "urls": [
                    "https://api.github.com/repos/thephpleague/commonmark/zipball/c493585c130544c4e91d2e0e131e6d35cb0cbc47"
                ],
                "cacheFile": "league/commonmark/378a63195644b8080db12fb35208f3fc3ab8acf0.zip",
                "sha256": "4a2af02687a4966271285dc1ccff0f2af2192396b6ee1097a53dc7d4ba23bc7c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "league_config-1.2.0.0",
                "urls": [
                    "https://api.github.com/repos/thephpleague/config/zipball/754b3604fb2984c71f4af4a9cbe7b57f346ec1f3"
                ],
                "cacheFile": "league/config/63acc0c0da84dd8710b3a4e58a6a4e393530da19.zip",
                "sha256": "1ad93a2858d4479e29d29b88d0d3e4ac4221631b06959454ae4061d058414b7a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "league_flysystem-3.12.2.0",
                "urls": [
                    "https://api.github.com/repos/thephpleague/flysystem/zipball/f6377c709d2275ed6feaf63e44be7a7162b0e77f"
                ],
                "cacheFile": "league/flysystem/e9a3840718adf9cea0aefabeedff286672a14977.zip",
                "sha256": "a5de3dfe00551c7e471f2f01a52aa8ce5fe0d91b1456029991c9ca9ad9847839"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "league_mime-type-detection-1.11.0.0",
                "urls": [
                    "https://api.github.com/repos/thephpleague/mime-type-detection/zipball/ff6248ea87a9f116e78edd6002e39e5128a0d4dd"
                ],
                "cacheFile": "league/mime-type-detection/f9602cfc5f45723d4f590e49e3683471bec330cb.zip",
                "sha256": "dfed2ddf02aee15b220396813b02e48e0d662cd772233f26dbe333d3f0b6c3a8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "monolog_monolog-2.9.1.0",
                "urls": [
                    "https://api.github.com/repos/Seldaek/monolog/zipball/f259e2b15fb95494c83f52d3caad003bbf5ffaa1"
                ],
                "cacheFile": "monolog/monolog/af7bafa3cdde5eef658108caf24489923a658da0.zip",
                "sha256": "62ae7992cb222574556c8f276420097d72d5971113fd611881bab315f2a3e753"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nesbot_carbon-2.66.0.0",
                "urls": [
                    "https://api.github.com/repos/briannesbitt/Carbon/zipball/496712849902241f04902033b0441b269effe001"
                ],
                "cacheFile": "nesbot/carbon/8a5075a6ddae43266cd352e4dcc76e38a5f9673b.zip",
                "sha256": "1dece0c0233d97157105f55fa02faf1e0a138c6a4368bf0e97dea128195041af"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nette_schema-1.2.3.0",
                "urls": [
                    "https://api.github.com/repos/nette/schema/zipball/abbdbb70e0245d5f3bf77874cea1dfb0c930d06f"
                ],
                "cacheFile": "nette/schema/34af605f2e76f1123861e91e0fa1dae2bf859457.zip",
                "sha256": "b840b5cf98b9a7bd6edc3f34fdeef688106127e2ca917b015eb55e096a7c289a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nette_utils-4.0.0.0",
                "urls": [
                    "https://api.github.com/repos/nette/utils/zipball/cacdbf5a91a657ede665c541eda28941d4b09c1e"
                ],
                "cacheFile": "nette/utils/c420a850090625206da0b557fd85d53ede5655b4.zip",
                "sha256": "10d5131bf50b98dbf4d591d0223c931a3cf48e43c15382493b32e5da7ad16a6c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nunomaduro_termwind-1.15.1.0",
                "urls": [
                    "https://api.github.com/repos/nunomaduro/termwind/zipball/8ab0b32c8caa4a2e09700ea32925441385e4a5dc"
                ],
                "cacheFile": "nunomaduro/termwind/639200e9d07a30deac047f3f6a96c3738f7c49e1.zip",
                "sha256": "87da562a3e28fd7c23da12b61927d561a888d04247ee659a2f9a0470f0dde5bc"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpoption_phpoption-1.9.0.0",
                "urls": [
                    "https://api.github.com/repos/schmittjoh/php-option/zipball/dc5ff11e274a90cc1c743f66c9ad700ce50db9ab"
                ],
                "cacheFile": "phpoption/phpoption/bba71c7f765409778b1f6d984ec2a76bf6c28ddc.zip",
                "sha256": "ac2c05db82f6a407f3dbdf0ff8399888de94881cf21fd401333b9683057b298a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_container-2.0.2.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/container/zipball/c71ecc56dfe541dbd90c5360474fbc405f8d5963"
                ],
                "cacheFile": "psr/container/a0a43e15cb16e3ab95a991e1bffc813474b15cdf.zip",
                "sha256": "3111f5b69d3a0f690f5f92d7aeacfb247f5ebd3c175088cce4b098e5d1b06ad7"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_event-dispatcher-1.0.0.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/event-dispatcher/zipball/dbefd12671e8a14ec7f180cab83036ed26714bb0"
                ],
                "cacheFile": "psr/event-dispatcher/8f60a8cd1b7ff4e8f9782d70d78dee877a526529.zip",
                "sha256": "4d6a674cfd89a9957ead82e31ee4df785b2b1d215693add73184729a9a66d116"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_log-3.0.0.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/log/zipball/fe5ea303b0887d5caefd3d431c3e61ad47037001"
                ],
                "cacheFile": "psr/log/4109d4b3f74b78a13cb175029bcb2384f59f0a52.zip",
                "sha256": "bbc23516c85615f2f85b707bc10ba26e62033e2afd696e075575b68dc6e31928"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_simple-cache-3.0.0.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/simple-cache/zipball/764e0b3939f5ca87cb904f570ef9be2d78a07865"
                ],
                "cacheFile": "psr/simple-cache/f30344b376a5fb0289c0491e8df6aba973ba12aa.zip",
                "sha256": "e899e363a85c26b3f1a621182b6eed2a37a71d823410ac949a1cbfd4b655ec41"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "ramsey_collection-1.3.0.0",
                "urls": [
                    "https://api.github.com/repos/ramsey/collection/zipball/ad7475d1c9e70b190ecffc58f2d989416af339b4"
                ],
                "cacheFile": "ramsey/collection/609254bce64f8f9b1560ddf857e5160226731562.zip",
                "sha256": "dcfd8c05f6549d7c93a9fb08606f31228c9c59e2536815a170f3afdc78c33ca8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "ramsey_uuid-4.7.3.0",
                "urls": [
                    "https://api.github.com/repos/ramsey/uuid/zipball/433b2014e3979047db08a17a205f410ba3869cf2"
                ],
                "cacheFile": "ramsey/uuid/7e784b222d66ef4b7c47789873e19f004ed2c87c.zip",
                "sha256": "122dad63cf9c3c4158b72dc5c9d79dc2a2e5bcbaeff12f7fd8ff5bbade5a6dfb"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_console-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/console/zipball/c3ebc83d031b71c39da318ca8b7a07ecc67507ed"
                ],
                "cacheFile": "symfony/console/cf1079e94604413572fdb9c8077dac3dca76a928.zip",
                "sha256": "d786f534c0ae5b1d621b2e5ac30c87145803e2d53a8252113aa923f09ce06def"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_css-selector-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/css-selector/zipball/f1d00bddb83a4cb2138564b2150001cb6ce272b1"
                ],
                "cacheFile": "symfony/css-selector/700fcf276a5861153a03647e75bfaaf0bda33fb5.zip",
                "sha256": "911c0274fb3eae232b0ca70d1bdc091506f81b997c039f7af6a4ea922527895a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_deprecation-contracts-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/symfony/deprecation-contracts/zipball/26954b3d62a6c5fd0ea8a2a00c0353a14978d05c"
                ],
                "cacheFile": "symfony/deprecation-contracts/4d47eca6ee854e21b5f9e5f3b411189f019bd558.zip",
                "sha256": "b70da9d9324b76f55b2ef8afbb11f45c3b59353dcecb27527e55faf56c928af2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_error-handler-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/error-handler/zipball/c7df52182f43a68522756ac31a532dd5b1e6db67"
                ],
                "cacheFile": "symfony/error-handler/4362d8dc8940e32a8626557fd58d2710814db8a8.zip",
                "sha256": "889ded73433e7b5b6d6883d7f2fc14cbc7f9f30dffa27eb049b37ec3870519b7"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_event-dispatcher-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/event-dispatcher/zipball/2eaf8e63bc5b8cefabd4a800157f0d0c094f677a"
                ],
                "cacheFile": "symfony/event-dispatcher/a750d7e7582528dfc9f4323bc9db63e44636ca0e.zip",
                "sha256": "567bf06bb91ab50220e74d2d66bd80fd07ba21c673c0461f17a0d82060879773"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_event-dispatcher-contracts-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/symfony/event-dispatcher-contracts/zipball/7bc61cc2db649b4637d331240c5346dcc7708051"
                ],
                "cacheFile": "symfony/event-dispatcher-contracts/209216ef5d7de22ca666c1d9ae275b3a79137b63.zip",
                "sha256": "91f051a5b67196f07ca500d5b75769cedf9fb24a219dc91d01c9caf288143db3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_finder-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/finder/zipball/5cc9cac6586fc0c28cd173780ca696e419fefa11"
                ],
                "cacheFile": "symfony/finder/817d215ed4fd7554a45f2763e8517638d731b938.zip",
                "sha256": "ac898e03564ce34448dc7b4d6ecf7372e6f61dd4593036c0ea3f33fe595f1ab8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_http-foundation-6.0.20.0",
                "urls": [
                    "https://api.github.com/repos/symfony/http-foundation/zipball/e16b2676a4b3b1fa12378a20b29c364feda2a8d6"
                ],
                "cacheFile": "symfony/http-foundation/45a020b64d79b7780487503081036f1e9c4e436d.zip",
                "sha256": "4f908b221915c63d4cc65eb64ec3ece19aacdd9de2d140913c589fd8d97f4e34"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_http-kernel-6.0.20.0",
                "urls": [
                    "https://api.github.com/repos/symfony/http-kernel/zipball/6dc70833fd0ef5e861e17c7854c12d7d86679349"
                ],
                "cacheFile": "symfony/http-kernel/6a1c18a8a9008a05ad1e8d8ac14e562b677c4d3e.zip",
                "sha256": "59480623f65632124f8a9ddb9e1999416294fc790193f0243f5d5bf242483fc8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_mailer-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/mailer/zipball/cd60799210c488f545ddde2444dc1aa548322872"
                ],
                "cacheFile": "symfony/mailer/9afcb0db1edfbc38a1557017984c15ef8e2059d8.zip",
                "sha256": "c715bfbba229ed059413c7727903fc57a5424740d1d394802c8c92ed5368afef"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_mime-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/mime/zipball/d7052547a0070cbeadd474e172b527a00d657301"
                ],
                "cacheFile": "symfony/mime/97dd79548f9a68459d2c0b3801017bb73992c73e.zip",
                "sha256": "8a09b1fd03b9b95a6352692798f3b06674192509d0cfb0311617d9c62e73b200"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-ctype-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-ctype/zipball/5bbc823adecdae860bb64756d639ecfec17b050a"
                ],
                "cacheFile": "symfony/polyfill-ctype/04e84c03a82a82c09eaa688b17b523570f9d14d2.zip",
                "sha256": "66f212bc73088271dbbec1f3b1c3ba21171e4c5ab38676c4d151441f3e38db6f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-intl-grapheme-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-intl-grapheme/zipball/511a08c03c1960e08a883f4cffcacd219b758354"
                ],
                "cacheFile": "symfony/polyfill-intl-grapheme/3e0defb9f075160deb0ea7188610275ee40a9b00.zip",
                "sha256": "11c409622d2321bfdd2fd1efdbdeaaba95da5211256f6cfdb4e003d7bd7eda45"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-intl-idn-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-intl-idn/zipball/639084e360537a19f9ee352433b84ce831f3d2da"
                ],
                "cacheFile": "symfony/polyfill-intl-idn/c8495253150c4daacaf90487f77a76fc7122c16b.zip",
                "sha256": "b2ff6b6408861c6c8c486fcb3bd2109438d5d6ced9175250cfbef1e596665cc4"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-intl-normalizer-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-intl-normalizer/zipball/19bd1e4fcd5b91116f14d8533c57831ed00571b6"
                ],
                "cacheFile": "symfony/polyfill-intl-normalizer/3282f96073427a186419bc5ae65aa6726d0f143b.zip",
                "sha256": "22bf30d7b50aabe1846e3ffbc03011903e05f4208d3bb49b373c4e5fe09500b5"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-mbstring-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-mbstring/zipball/8ad114f6b39e2c98a8b0e3bd907732c207c2b534"
                ],
                "cacheFile": "symfony/polyfill-mbstring/7061da8bfb2a98acfbdcaf076c3ba5f167d856cc.zip",
                "sha256": "b112101451a1f76a0cb4edd6595a5733059fd2f7a4cd4d36052526602e26a8fa"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-php72-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-php72/zipball/869329b1e9894268a8a61dabb69153029b7a8c97"
                ],
                "cacheFile": "symfony/polyfill-php72/3dc6f2e0efb0a915be032510852eb9fb9205577c.zip",
                "sha256": "973b3eaa88a3e4d3287b336c4a3e057feca1f9f703f05abd234a07d2105c14c0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-php80-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-php80/zipball/7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936"
                ],
                "cacheFile": "symfony/polyfill-php80/fe4df98f0392f59ca247eec4d07f380451c09242.zip",
                "sha256": "8db38ad9c85c94ad664b89ff9ec9dd5b232dc922f6107bb356d44e9dcf6cde9b"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-php81-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-php81/zipball/707403074c8ea6e2edaf8794b0157a0bfa52157a"
                ],
                "cacheFile": "symfony/polyfill-php81/05342953cef79782b0eb31a71035b4ad15818809.zip",
                "sha256": "2e09d990064b80c605ac1d7b112895f0dc98e96a1e541e0215807c6bad931917"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-uuid-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-uuid/zipball/f3cf1a645c2734236ed1e2e671e273eeb3586166"
                ],
                "cacheFile": "symfony/polyfill-uuid/826ec113493cd406218c5342c1c2a6449bb6f926.zip",
                "sha256": "ac1e3e9868ce26d0785126c1f900c1712dc2993a31b954b30bc7511e834150de"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_process-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/process/zipball/2114fd60f26a296cc403a7939ab91478475a33d4"
                ],
                "cacheFile": "symfony/process/3c60abc2e78096e563e0c71e5e759016c1640de0.zip",
                "sha256": "0173ba96a9e6a7047ca7ae54f2ac4684ba93c7d18495649df61238af30a0ece6"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_routing-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/routing/zipball/e56ca9b41c1ec447193474cd86ad7c0b547755ac"
                ],
                "cacheFile": "symfony/routing/7242dcfc97457e627bfab0b1058f89107392473b.zip",
                "sha256": "cd961a453c1d65e9c90b17a19b7b142f3386efdf8a229bcb33dd62e88a285d63"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_service-contracts-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/symfony/service-contracts/zipball/d78d39c1599bd1188b8e26bb341da52c3c6d8a66"
                ],
                "cacheFile": "symfony/service-contracts/880c3cc97a5424e1989454dd2041c0ebdf3dc84e.zip",
                "sha256": "29fd011c3a70250cf370c8a0d774c82e721e636ebba016d860d93bd1bdb0ebb1"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_string-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/string/zipball/d9e72497367c23e08bf94176d2be45b00a9d232a"
                ],
                "cacheFile": "symfony/string/e796042fe8f8b82e77830831c7c6d53392aef0ef.zip",
                "sha256": "ee429a33627423a81f054759a7d1683b026b1ab299e0ff50b44ddce624db9b4c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_translation-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/translation/zipball/9c24b3fdbbe9fb2ef3a6afd8bbaadfd72dad681f"
                ],
                "cacheFile": "symfony/translation/c54c98fab1ed0ac0cbe6903e9903620c372e606c.zip",
                "sha256": "a2139db9ba1292d47e2d6266838087c7d00af69d1389dbd133003249cb1c8189"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_translation-contracts-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/symfony/translation-contracts/zipball/acbfbb274e730e5a0236f619b6168d9dedb3e282"
                ],
                "cacheFile": "symfony/translation-contracts/44eea647999ae98fd8a3ebe8f7b3f5c2c3969eeb.zip",
                "sha256": "20e3f9edc8716e64bd7119b11f88c391b07a5550d89cae0064031b358c3489e4"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_uid-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/uid/zipball/6499e28b0ac9f2aa3151e11845bdb5cd21e6bb9d"
                ],
                "cacheFile": "symfony/uid/9dc2201074603f53e12be934d3a87310e4aff6ea.zip",
                "sha256": "d8ff73fdc0c37f2ca039892476a5fd8c44e3618062d57715c11532ceeb93228b"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_var-dumper-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/var-dumper/zipball/eb980457fa6899840fe1687e8627a03a7d8a3d52"
                ],
                "cacheFile": "symfony/var-dumper/90b70e68fa941316917bae41e2d65a393682df40.zip",
                "sha256": "53b02741e18dfc79c9b2f8f5e037ad0189c55379f7ab837d97749213897e71a0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "tijsverkoyen_css-to-inline-styles-2.2.6.0",
                "urls": [
                    "https://api.github.com/repos/tijsverkoyen/CssToInlineStyles/zipball/c42125b83a4fa63b187fdf29f9c93cb7733da30c"
                ],
                "cacheFile": "tijsverkoyen/css-to-inline-styles/3dcc27d0fe326e27f50c5246f9de9d4562918729.zip",
                "sha256": "ad8d7e16f1217b1cd05a76460a56e0d632d960ee270291dd6c0e7cce21017332"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "vlucas_phpdotenv-5.5.0.0",
                "urls": [
                    "https://api.github.com/repos/vlucas/phpdotenv/zipball/1a7ea2afc49c3ee6d87061f5a233e3a035d0eae7"
                ],
                "cacheFile": "vlucas/phpdotenv/3768c8e216b4bb1af0c65a5a317f69502a0cefde.zip",
                "sha256": "0a08638e844488287a307fe9f5a2d2aeec0c84848dadcefab1c1ca06bbef048e"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "voku_portable-ascii-2.0.1.0",
                "urls": [
                    "https://api.github.com/repos/voku/portable-ascii/zipball/b56450eed252f6801410d810c8e1727224ae0743"
                ],
                "cacheFile": "voku/portable-ascii/d530a9779b65656e504bf4b013e19c70336ba351.zip",
                "sha256": "d45b55bc98e466a41369c4d9a034aa9721a614a7dbde30237299799361d8943f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "webmozart_assert-1.11.0.0",
                "urls": [
                    "https://api.github.com/repos/webmozarts/assert/zipball/11cb2199493b2f8a3b53e7f19068fc6aac760991"
                ],
                "cacheFile": "webmozart/assert/b9bc0224905e92da07bc3de7d205f17c30035a88.zip",
                "sha256": "3dea7b980d4ba44fca74fbd1d068be28f1a771e1a1cb308e89b773eb83fa11a3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "doctrine_instantiator-1.5.0.0",
                "urls": [
                    "https://api.github.com/repos/doctrine/instantiator/zipball/0a0fa9780f5d4e507415a065172d26a98d02047b"
                ],
                "cacheFile": "doctrine/instantiator/281539f78a082d6b6f518e4643e807bb44376df5.zip",
                "sha256": "b2ac699a2ce6afe19db094650009e81eb0471d8cbfaa7a8bb4825e88e6011b03"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "drupol_composer-plugin-nixify-9999999-dev",
                "urls": [
                    "https://api.github.com/repos/drupol/composer-plugin-nixify/zipball/fd8faf5b898f5366c9d107eb407360b41a477b8f"
                ],
                "cacheFile": "drupol/composer-plugin-nixify/b520a1e323394de2e25d37bf63b8627c8748b840.zip",
                "sha256": "608a34aa52abc812f29b0834ea1334d6c5792cfd12bac20400156f5199819b0e"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "fakerphp_faker-1.21.0.0",
                "urls": [
                    "https://api.github.com/repos/FakerPHP/Faker/zipball/92efad6a967f0b79c499705c69b662f738cc9e4d"
                ],
                "cacheFile": "fakerphp/faker/c387cdf732974b91a1e0584128660a6c5e55eb2f.zip",
                "sha256": "0f5fb279714dd488d76efb56abc6f3f94977209c9d6aa7bb2ccc83cde226b47b"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "guzzlehttp_psr7-2.4.3.0",
                "urls": [
                    "https://api.github.com/repos/guzzle/psr7/zipball/67c26b443f348a51926030c83481b85718457d3d"
                ],
                "cacheFile": "guzzlehttp/psr7/f029e31b3f0f082aed4213b0cf7953278f2018b2.zip",
                "sha256": "8fa79e2da503be7c4b1a91aeafa1bf303b7f3d48fca7dd8bba8efffa7b815b25"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "hamcrest_hamcrest-php-2.0.1.0",
                "urls": [
                    "https://api.github.com/repos/hamcrest/hamcrest-php/zipball/8c3d0a3f6af734494ad8f6fbbee0ba92422859f3"
                ],
                "cacheFile": "hamcrest/hamcrest-php/f7a45641934dde6189dd47e6355c3290a81916b1.zip",
                "sha256": "191a65145df949136993b3b512f78f6c492cc8082e35329c193f3845efadb5c7"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "mockery_mockery-1.5.1.0",
                "urls": [
                    "https://api.github.com/repos/mockery/mockery/zipball/e92dcc83d5a51851baf5f5591d32cb2b16e3684e"
                ],
                "cacheFile": "mockery/mockery/b142beadab180dfadb0f0e98fcea36165236eb60.zip",
                "sha256": "49173ea9cb2e2540e1072875808e92ae44238de0581f2d8e36969de11cc87337"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "myclabs_deep-copy-1.11.0.0",
                "urls": [
                    "https://api.github.com/repos/myclabs/DeepCopy/zipball/14daed4296fae74d9e3201d2c4925d1acb7aa614"
                ],
                "cacheFile": "myclabs/deep-copy/8a47e905abc875fa8049c320097a46a9c305b50b.zip",
                "sha256": "3c357c9554caa4d6d71117ce8cfb7db23c1ac64eb28a1e659988cbcf201ba984"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nikic_php-parser-4.15.3.0",
                "urls": [
                    "https://api.github.com/repos/nikic/PHP-Parser/zipball/570e980a201d8ed0236b0a62ddf2c9cbb2034039"
                ],
                "cacheFile": "nikic/php-parser/d82d7114a2384784c2ec20cf1dd8fd2ac538f2ba.zip",
                "sha256": "b9d68a41dc37fdb939e2200911ac0610fd37e4169a3171a0eb3a13e5e5b570e0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nunomaduro_larastan-2.4.0.0",
                "urls": [
                    "https://api.github.com/repos/nunomaduro/larastan/zipball/14f631348ead3e245651606931863b4f218d1f78"
                ],
                "cacheFile": "nunomaduro/larastan/a74be995c5230d5508a5a72d8d31c042f4f924d1.zip",
                "sha256": "a8afdf80aa6bc1fe43f5e7a5828e5d5940584e966178ad6a9033ef9c79c934f5"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "orchestra_testbench-7.22.0.0",
                "urls": [
                    "https://api.github.com/repos/orchestral/testbench/zipball/4e16b1adde9d13aff6e4221c841bb82dcd4416f0"
                ],
                "cacheFile": "orchestra/testbench/92be2777b8de014e914c04abcaf41478c8bfc963.zip",
                "sha256": "6966cd08be1a83490d446a63652c5f3f590800e2d45cf6183ef3c8b6605200d9"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "orchestra_testbench-core-7.22.0.0",
                "urls": [
                    "https://api.github.com/repos/orchestral/testbench-core/zipball/a6e4240149ffc1bb3068a68fe4261a5b59753079"
                ],
                "cacheFile": "orchestra/testbench-core/ba3c890ebe6eeafb6ca3bc573c8fb6b1c2069d00.zip",
                "sha256": "36daa646733765b47ea81d1f4a35a0a45cd1caecd0c1cf76828c1bfb6f7740b5"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phar-io_manifest-2.0.3.0",
                "urls": [
                    "https://api.github.com/repos/phar-io/manifest/zipball/97803eca37d319dfa7826cc2437fc020857acb53"
                ],
                "cacheFile": "phar-io/manifest/99001d1a4fa9041c56147e32147fb55de1cf9383.zip",
                "sha256": "3cb072c02dc066ff22531c8bb5bdf1a4e1dca6207c378218f75c4f4680d4ed80"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phar-io_version-3.2.1.0",
                "urls": [
                    "https://api.github.com/repos/phar-io/version/zipball/4f7fd7836c6f332bb2933569e566a0d6c4cbed74"
                ],
                "cacheFile": "phar-io/version/1495d1d88b1ae7e031b437037ce96298d897a969.zip",
                "sha256": "4f6f4fab8bfeac95934cec75be23743e38b6d864876f52dcdd5b54e003fcab55"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpmyadmin_sql-parser-5.7.0.0",
                "urls": [
                    "https://api.github.com/repos/phpmyadmin/sql-parser/zipball/0f5895aab2b6002d00b6831b60983523dea30bff"
                ],
                "cacheFile": "phpmyadmin/sql-parser/5c727e6d7d9abd74804a5dda573ffbce21d87971.zip",
                "sha256": "5c090ca10aad1e8390ee7639b132272c9d4da173c221d0adad90dcdf5eb3d204"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-1.9.17.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan/zipball/204e459e7822f2c586463029f5ecec31bb45a1f2"
                ],
                "cacheFile": "phpstan/phpstan/9cfa004e0e697525d593fb2914d439a9c4221609.zip",
                "sha256": "b5c7eb2350e91ed1e19dfebbe56d12aad202b951bfc8dfab8a0ee058352a9c76"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-phpunit-1.3.4.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan-phpunit/zipball/d77af96c1aaec28f7c0293677132eaaad079e01b"
                ],
                "cacheFile": "phpstan/phpstan-phpunit/094e089a621e8a8f735c95f3823e0ca5a1fc0d47.zip",
                "sha256": "4616659fcef11c89f6c7dfd7011b382624e816ec3287e0213c23cd5c2623af0f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-strict-rules-1.4.5.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan-strict-rules/zipball/361f75b06066f3fdaba87c1f57bdb1ffc28d6f1d"
                ],
                "cacheFile": "phpstan/phpstan-strict-rules/a61fa77a7a0b3524e0a2ea685491e897818d534b.zip",
                "sha256": "506bc225e063b457682b0b4742ff5bc0900201702dd963ea731e06b1bd001eea"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-code-coverage-9.2.24.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-code-coverage/zipball/2cf940ebc6355a9d430462811b5aaa308b174bed"
                ],
                "cacheFile": "phpunit/php-code-coverage/22950ed3ec19594703b2c51ce0c35f7e8c502d87.zip",
                "sha256": "ea8717edadc67bd1817b2d4a79cedc7e5540b0ff3ae984655df32dc6b13bb2d2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-file-iterator-3.0.6.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-file-iterator/zipball/cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf"
                ],
                "cacheFile": "phpunit/php-file-iterator/4fd4ef934d9b090aff1c14e5987f251c5d6b2d0c.zip",
                "sha256": "d9b2fe0929a3a844490dd9d32dbbd09a19713e3356e0199b26bc0c181c6a0790"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-invoker-3.1.1.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-invoker/zipball/5a10147d0aaf65b58940a0b72f71c9ac0423cc67"
                ],
                "cacheFile": "phpunit/php-invoker/18d90380b8ff6f566265ca070b4bcfe4c4bbd34c.zip",
                "sha256": "d091fc2206ce86ff8664068b04952c8d8ff6dc12b7d864c1a8bf92c4adb416ef"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-text-template-2.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-text-template/zipball/5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28"
                ],
                "cacheFile": "phpunit/php-text-template/b8d58f7d3789d6fd84cb6a82ebcb5776ab609787.zip",
                "sha256": "98a2b504e34e4b99e433f6d738b877d5847ea9b2800f7d8534f147eebf3fc839"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-timer-5.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-timer/zipball/5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2"
                ],
                "cacheFile": "phpunit/php-timer/b71ded866a460bbdb922b5eb818f4ed163f38f0c.zip",
                "sha256": "cacc8ec54d593bfaa1627bc67e110b0ef9d2f1d2ae98007d8b2bcc4fbc3f2f3c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_phpunit-9.6.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/phpunit/zipball/e7b1615e3e887d6c719121c6d4a44b0ab9645555"
                ],
                "cacheFile": "phpunit/phpunit/43638934ebf3cb1d505efcd402ac91eee55732e5.zip",
                "sha256": "7a248a5f760d15264e4cc3b116b5234c9fb5b6f8d9a22c470e5c61d5e97eebdc"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "pimple_pimple-3.5.0.0",
                "urls": [
                    "https://api.github.com/repos/silexphp/Pimple/zipball/a94b3a4db7fb774b3d78dad2315ddc07629e1bed"
                ],
                "cacheFile": "pimple/pimple/2b779ca4c5368b4bd2cbf2aff634d10a209c763f.zip",
                "sha256": "f4a26a6a701bdeb7c90c19e8355cb8ea5ffd3a4505c22bf72e45fb873d03b8f1"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_http-factory-1.0.1.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/http-factory/zipball/12ac7fcd07e5b077433f5f2bee95b3a771bf61be"
                ],
                "cacheFile": "psr/http-factory/554dafa2f4680a78fa693cedcbe62bc6873809db.zip",
                "sha256": "baedc0aa21248f8a0316a8b78c98754cf7c4b3fe8ab7a4da5ad0adc22eb6cb46"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_http-message-1.0.1.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/http-message/zipball/f6561bf28d520154e4b0ec72be95418abe6d9363"
                ],
                "cacheFile": "psr/http-message/cc1d4e9ee13f2053b80c08976256789bf3be5256.zip",
                "sha256": "8538467ca2665fe15574f4d2506871823f71fd24b9a9284aae2ba90d8f69ada4"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "ralouphie_getallheaders-3.0.3.0",
                "urls": [
                    "https://api.github.com/repos/ralouphie/getallheaders/zipball/120b605dfeb996808c31b6477290a714d356e822"
                ],
                "cacheFile": "ralouphie/getallheaders/ddc5f4c7ab3d868f5060717336a0d93475d53175.zip",
                "sha256": "ef0165da5690da666ab4cb88bb4cec0d50372e3e7c922532c5795a3567b367af"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_cli-parser-1.0.1.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/cli-parser/zipball/442e7c7e687e42adc03470c7b668bc4b2402c0b2"
                ],
                "cacheFile": "sebastian/cli-parser/f4b297cc8d9ba3ba47f6d1c84b9d69bac882a7b1.zip",
                "sha256": "6740017ab612481526b458876d8a9aba23326099ca0e0cb7263dcd1470fb981c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_code-unit-1.0.8.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/code-unit/zipball/1fc9f64c0927627ef78ba436c9b17d967e68e120"
                ],
                "cacheFile": "sebastian/code-unit/2175508c3a7c4f57c236668e95692cb4f230ef7e.zip",
                "sha256": "f51e89b8ecce2a310a2cef0d7e8256378540fe1da91daa7a25a5e50c0ae87413"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_code-unit-reverse-lookup-2.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/code-unit-reverse-lookup/zipball/ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5"
                ],
                "cacheFile": "sebastian/code-unit-reverse-lookup/68fb878dfd88a53caa52899dcad6f00ede9925b2.zip",
                "sha256": "4a6a9beb03ba89c65df74e0200eef997aed640f362a94a224e61aa3ffe5f32c0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_comparator-4.0.8.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/comparator/zipball/fa0f136dd2334583309d32b62544682ee972b51a"
                ],
                "cacheFile": "sebastian/comparator/6a8576886b5e1cfd55783584d8a948ab21adc37c.zip",
                "sha256": "7ca0bc15be7811ff9964e059889466bab579a93f7ed34cd02e58f0aef85c1155"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_complexity-2.0.2.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/complexity/zipball/739b35e53379900cc9ac327b2147867b8b6efd88"
                ],
                "cacheFile": "sebastian/complexity/76ac0bc95bb26576a1588ac4917fe13f3107573f.zip",
                "sha256": "ce23bcd6c0fe24007e0ad6bf3cc17fa7beedf11dfdc6e46c84eb6b882cfa9ef8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_diff-4.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/diff/zipball/3461e3fccc7cfdfc2720be910d3bd73c69be590d"
                ],
                "cacheFile": "sebastian/diff/527dd851ed7cdbd6b86e440441567b594e489fde.zip",
                "sha256": "b209732f1736f8eb065781ac87b69bc0d8a752f19df0813ed820dbc60cb5c724"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_environment-5.1.5.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/environment/zipball/830c43a844f1f8d5b7a1f6d6076b784454d8b7ed"
                ],
                "cacheFile": "sebastian/environment/2233d3b38ac6d485959f6c153c851f07547fee65.zip",
                "sha256": "f653465ac3278f2109df985a8cfab6bb8a0524f4f0861d4e993f001b872d0408"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_exporter-4.0.5.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/exporter/zipball/ac230ed27f0f98f597c8a2b6eb7ac563af5e5b9d"
                ],
                "cacheFile": "sebastian/exporter/d097047a341fb0e411c70e540a62a9ca3af9479c.zip",
                "sha256": "d290d6d4c1ed86927a833cc9cceb9fefb4b55d6cda7774e38b43f28c3692dea8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_global-state-5.0.5.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/global-state/zipball/0ca8db5a5fc9c8646244e629625ac486fa286bf2"
                ],
                "cacheFile": "sebastian/global-state/1cf3bc48e84c37ec54b03a90443ac94230cef95b.zip",
                "sha256": "e14d22f89153d22e02b21b305a34258e43992ef7ab3a2ac2517fc7b38a7259b3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_lines-of-code-1.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/lines-of-code/zipball/c1c2e997aa3146983ed888ad08b15470a2e22ecc"
                ],
                "cacheFile": "sebastian/lines-of-code/c83c674fbb96cf1b9525472250a2ec5c8e7784d6.zip",
                "sha256": "60ae97d500e9d96e826afb01b5789c511fdb7fe6304a7c325fcf84ca8a4e5e39"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_object-enumerator-4.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/object-enumerator/zipball/5c9eeac41b290a3712d88851518825ad78f45c71"
                ],
                "cacheFile": "sebastian/object-enumerator/da625947c9c4e28182677035866359692138e8aa.zip",
                "sha256": "c132dcacda3e4e0967aeabf068fa83f3f492a351c34bcd8f5101227ec01f0585"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_object-reflector-2.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/object-reflector/zipball/b4f479ebdbf63ac605d183ece17d8d7fe49c15c7"
                ],
                "cacheFile": "sebastian/object-reflector/89595d8936651649889c35a91221207e12331fda.zip",
                "sha256": "4f673297cc7e85c41c8658c202e01ead4adae48d6c870ec070941bcfb50bb53c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_recursion-context-4.0.5.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/recursion-context/zipball/e75bd0f07204fec2a0af9b0f3cfe97d05f92efc1"
                ],
                "cacheFile": "sebastian/recursion-context/4b7cea85c6a1d0a92ff75035f6b0545625890a5f.zip",
                "sha256": "8102972caec5c2041cb1b156913ac9a320cca9943dc94cde79be43e7baf6e6a9"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_resource-operations-3.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/resource-operations/zipball/0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8"
                ],
                "cacheFile": "sebastian/resource-operations/c70bff160e611fd40d5d68d1f06d580b9496fb3a.zip",
                "sha256": "d92f4b5b50d5e264d3b00ab31a3b80c0718f2689a1f3f23d101ce67a6e46ba5c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_type-3.2.1.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/type/zipball/75e2c2a32f5e0b3aef905b9ed0b179b953b3d7c7"
                ],
                "cacheFile": "sebastian/type/6c52c952769f461058a7bcc9db2baadd3633dfc8.zip",
                "sha256": "8507e504e5e67b8ac937a96373d980464fd8c1fa7211dd3f14fe2e2cccda6e2f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_version-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/version/zipball/c6c1022351a901512170118436c764e473f6de8c"
                ],
                "cacheFile": "sebastian/version/85e202da271e8389420827021d6c4f00bdd90951.zip",
                "sha256": "e1c5424e05207360f511745290144dcad1df69f1789fd97eb0d1819a145f47af"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "spatie_backtrace-1.2.1.0",
                "urls": [
                    "https://api.github.com/repos/spatie/backtrace/zipball/4ee7d41aa5268107906ea8a4d9ceccde136dbd5b"
                ],
                "cacheFile": "spatie/backtrace/811457da95b29639b118f7546cc4861dff48d711.zip",
                "sha256": "2b14ae9b84c591f84793567ca36ea8aa971ea7ef1c7172382d8d6e1a66c46d3e"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "spatie_laravel-ray-1.32.2.0",
                "urls": [
                    "https://api.github.com/repos/spatie/laravel-ray/zipball/0c28a8274ec261a2857b4318b6f934af98024395"
                ],
                "cacheFile": "spatie/laravel-ray/313c2316dd2b0743ad7e34d4bf042894ff3da1b5.zip",
                "sha256": "19d5d6be63aeedab7b1c6c46641192172e79aca9716f64020a35d2ddbb5d3745"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "spatie_macroable-2.0.0.0",
                "urls": [
                    "https://api.github.com/repos/spatie/macroable/zipball/ec2c320f932e730607aff8052c44183cf3ecb072"
                ],
                "cacheFile": "spatie/macroable/16c032bbb18e909bae8fd4affb4ab973ffcf6d11.zip",
                "sha256": "49484ae4277901ec1b077f2dd7501c72bb2c8e21e4779d9324114fb66ddc28ac"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "spatie_ray-1.36.2.0",
                "urls": [
                    "https://api.github.com/repos/spatie/ray/zipball/71dfde21900447ab37698fc07ff28b7f1e1822b8"
                ],
                "cacheFile": "spatie/ray/d9f89867e77226c0ef618dfa1ac61e3d55c2f16f.zip",
                "sha256": "9dc31b2ad7167056b62d32d0661565cff710fe1ca1ec1040a4eaa9129cce1a00"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "squizlabs_php_codesniffer-3.7.1.0",
                "urls": [
                    "https://api.github.com/repos/squizlabs/PHP_CodeSniffer/zipball/1359e176e9307e906dc3d890bcc9603ff6d90619"
                ],
                "cacheFile": "squizlabs/php_codesniffer/87828c804599927aa873e78e73b71ea8ed2dc48e.zip",
                "sha256": "41d8bad949966238289179ca65792e9b119fcf650a0e1a1dd7e0f51cbf00eb2d"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-iconv-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-iconv/zipball/927013f3aac555983a5059aada98e1907d842695"
                ],
                "cacheFile": "symfony/polyfill-iconv/69e48eceddb28b2d5879869d36e2ca37c03b236a.zip",
                "sha256": "099017cb34e1eb1d9c7ab60d5ff0919afb66520151a14c50cf65509147fbb6e2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_stopwatch-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/stopwatch/zipball/011e781839dd1d2eb8119f65ac516a530f60226d"
                ],
                "cacheFile": "symfony/stopwatch/a4143cd576cbe3530e82e5d0881901b4615b8028.zip",
                "sha256": "1bdeed0af76f5feadae2b422d0002ef3564556b93ff9c2d81e0668c3610de356"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_yaml-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/yaml/zipball/deec3a812a0305a50db8ae689b183f43d915c884"
                ],
                "cacheFile": "symfony/yaml/0bbb17de1541d6ccc9dfacde00c0436ebb4afb25.zip",
                "sha256": "22fc742c11f74845358d2892c734d6dd61bfe263169a2ea308b63a2b8b0b26e2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "theseer_tokenizer-1.2.1.0",
                "urls": [
                    "https://api.github.com/repos/theseer/tokenizer/zipball/34a41e998c2183e22995f158c581e7b5e755ab9e"
                ],
                "cacheFile": "theseer/tokenizer/9c419ba4ed9d43ff57a21270f44363ad0bed22f7.zip",
                "sha256": "18d8c32441b19070ed7643321f5d3d5ee07217b991bee605cf64c979025044fd"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "zbateson_mail-mime-parser-2.3.0.0",
                "urls": [
                    "https://api.github.com/repos/zbateson/mail-mime-parser/zipball/d59e0c5eeb1442fca94bcb3b9d3c6be66318a500"
                ],
                "cacheFile": "zbateson/mail-mime-parser/c6e12915fed7ded7517b129446ecefc269fe33a4.zip",
                "sha256": "fea497fffc47f108044500034c37c86b8ef565502aa0014c7ae3e5a591175055"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "zbateson_mb-wrapper-1.2.0.0",
                "urls": [
                    "https://api.github.com/repos/zbateson/mb-wrapper/zipball/faf35dddfacfc5d4d5f9210143eafd7a7fe74334"
                ],
                "cacheFile": "zbateson/mb-wrapper/70311ea000441a2181418e62a7980fda719a6b07.zip",
                "sha256": "941d2749c80f15c66c117ffbba6619df42012ce3223478a7a6bf82243b1f234d"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "zbateson_stream-decorators-1.1.0.0",
                "urls": [
                    "https://api.github.com/repos/zbateson/stream-decorators/zipball/7466ff45d249c86b96267a83cdae68365ae1787e"
                ],
                "cacheFile": "zbateson/stream-decorators/bef2f4c75fb98cc65691cbd383cb34c047d3e029.zip",
                "sha256": "ba2fd43bee6498b3ec623d63c1fe3e6413dc8b2f7fd6a18689968f570300338b"
            }
        ],
        "projectName": "bdelespierre_laravel-blade-linter"
    }
  '';
  composerPath = data.composerPath or phpPackages.composer.src;
  cacheEntries = data.cacheEntries or [];
  localEntries = data.localEntries or [];

  # Shell snippet to collect all project dependencies.
  collectCacheScript = writeText "collect-cache.sh" (
    concatMapStrings (args: ''
      (
        cacheFile=${escapeShellArg args.cacheFile}
        cacheFilePath="$COMPOSER_CACHE_DIR/files/$cacheFile"
        mkdir -p "$(dirname "$cacheFilePath")"
        cp ${escapeShellArg (fetcher args)} "$cacheFilePath"
      )
    '')
    cacheEntries
  );

  replaceLocalPaths = writeText "replace-local-paths.sh" (
    concatMapStrings (args: ''
      sed -i -e "s|\"${args.string}\"|\"${args.path}\"|" composer.lock
    '')
    localEntries
  );
in
  stdenv.mkDerivation {
    name = data.projectName;
    inherit src;

    # Make sure the build uses the right PHP version everywhere.
    # Also include unzip for Composer.
    buildInputs = [php unzip];

    # Defines the shell alias to run Composer.
    postHook = ''
      composer () {
        php "$NIX_COMPOSER_PATH" "$@"
      }
    '';

    configurePhase = ''
      runHook preConfigure

      # Set the cache directory for Composer.
      export COMPOSER_CACHE_DIR="$NIX_BUILD_TOP/.composer/cache"

      # Build the cache directory contents.
      source ${collectCacheScript}

      # Replace local package paths with their Nix store equivalent.
      source ${replaceLocalPaths}

      # Store the absolute path to Composer for the 'composer' alias.
      export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

      # Run normal Composer install to complete dependency installation.
      composer install -n -o

      runHook postConfigure
    '';

    buildPhase = ''
      runHook preBuild
      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall

      mkdir -p $out/libexec $out/bin

      # Move the entire project to the output directory.
      mv $PWD "$out/libexec/$sourceRoot"
      cd "$out/libexec/$sourceRoot"

      # Update the path to Composer.
      export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

      # Invoke a plugin internal command to setup binaries.
      # composer nixify-install-bin "$out/bin"

      runHook postInstall
    '';

    passthru = {
      inherit php;
    };
  }
